<?php

namespace Database\Seeders;

use App\Models\Achievement;
use Illuminate\Database\Seeder;

class AchievementSeeder extends Seeder
{
    public function run(): void
    {
        $achievements = [
            // ===== WORKOUT COUNT ACHIEVEMENTS =====
            [
                'achievement_name' => 'First Workout',
                'description' => 'Complete your first workout session',
                'achievement_type' => 'workout_count',
                'criteria_json' => ['target_count' => 1],
                'points_value' => 25,
                'badge_icon' => 'barbell',
                'badge_color' => '#6B7280',
                'rarity_level' => 'common',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Getting Started',
                'description' => 'Complete 10 workout sessions',
                'achievement_type' => 'workout_count',
                'criteria_json' => ['target_count' => 10],
                'points_value' => 50,
                'badge_icon' => 'barbell',
                'badge_color' => '#6B7280',
                'rarity_level' => 'common',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Dedicated Trainer',
                'description' => 'Complete 25 workout sessions',
                'achievement_type' => 'workout_count',
                'criteria_json' => ['target_count' => 25],
                'points_value' => 75,
                'badge_icon' => 'barbell',
                'badge_color' => '#3B82F6',
                'rarity_level' => 'rare',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Fitness Warrior',
                'description' => 'Complete 50 workout sessions',
                'achievement_type' => 'workout_count',
                'criteria_json' => ['target_count' => 50],
                'points_value' => 100,
                'badge_icon' => 'fitness',
                'badge_color' => '#3B82F6',
                'rarity_level' => 'rare',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Century Club',
                'description' => 'Complete 100 workout sessions',
                'achievement_type' => 'workout_count',
                'criteria_json' => ['target_count' => 100],
                'points_value' => 150,
                'badge_icon' => 'trophy',
                'badge_color' => '#8B5CF6',
                'rarity_level' => 'epic',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Workout Master',
                'description' => 'Complete 200 workout sessions',
                'achievement_type' => 'workout_count',
                'criteria_json' => ['target_count' => 200],
                'points_value' => 250,
                'badge_icon' => 'medal',
                'badge_color' => '#F59E0B',
                'rarity_level' => 'legendary',
                'is_active' => true,
            ],

            // ===== STREAK ACHIEVEMENTS =====
            [
                'achievement_name' => '3-Day Spark',
                'description' => 'Maintain a 3-day workout streak',
                'achievement_type' => 'streak',
                'criteria_json' => ['target_streak' => 3],
                'points_value' => 25,
                'badge_icon' => 'flame',
                'badge_color' => '#6B7280',
                'rarity_level' => 'common',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Week Warrior',
                'description' => 'Maintain a 7-day workout streak',
                'achievement_type' => 'streak',
                'criteria_json' => ['target_streak' => 7],
                'points_value' => 50,
                'badge_icon' => 'flame',
                'badge_color' => '#6B7280',
                'rarity_level' => 'common',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Two Week Terror',
                'description' => 'Maintain a 14-day workout streak',
                'achievement_type' => 'streak',
                'criteria_json' => ['target_streak' => 14],
                'points_value' => 75,
                'badge_icon' => 'flame',
                'badge_color' => '#3B82F6',
                'rarity_level' => 'rare',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Month Master',
                'description' => 'Maintain a 30-day workout streak',
                'achievement_type' => 'streak',
                'criteria_json' => ['target_streak' => 30],
                'points_value' => 150,
                'badge_icon' => 'flame',
                'badge_color' => '#8B5CF6',
                'rarity_level' => 'epic',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Iron Will',
                'description' => 'Maintain a 60-day workout streak',
                'achievement_type' => 'streak',
                'criteria_json' => ['target_streak' => 60],
                'points_value' => 200,
                'badge_icon' => 'flame',
                'badge_color' => '#8B5CF6',
                'rarity_level' => 'epic',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Unstoppable',
                'description' => 'Maintain a 100-day workout streak',
                'achievement_type' => 'streak',
                'criteria_json' => ['target_streak' => 100],
                'points_value' => 300,
                'badge_icon' => 'bonfire',
                'badge_color' => '#F59E0B',
                'rarity_level' => 'legendary',
                'is_active' => true,
            ],

            // ===== CALORIE ACHIEVEMENTS =====
            [
                'achievement_name' => 'First Thousand',
                'description' => 'Burn 1,000 total calories',
                'achievement_type' => 'calories',
                'criteria_json' => ['target_calories' => 1000],
                'points_value' => 25,
                'badge_icon' => 'flame-outline',
                'badge_color' => '#6B7280',
                'rarity_level' => 'common',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Calorie Burner',
                'description' => 'Burn 5,000 total calories',
                'achievement_type' => 'calories',
                'criteria_json' => ['target_calories' => 5000],
                'points_value' => 75,
                'badge_icon' => 'flame-outline',
                'badge_color' => '#3B82F6',
                'rarity_level' => 'rare',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Heat Generator',
                'description' => 'Burn 10,000 total calories',
                'achievement_type' => 'calories',
                'criteria_json' => ['target_calories' => 10000],
                'points_value' => 125,
                'badge_icon' => 'flame',
                'badge_color' => '#8B5CF6',
                'rarity_level' => 'epic',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Calorie Crusher',
                'description' => 'Burn 25,000 total calories',
                'achievement_type' => 'calories',
                'criteria_json' => ['target_calories' => 25000],
                'points_value' => 175,
                'badge_icon' => 'flame',
                'badge_color' => '#8B5CF6',
                'rarity_level' => 'epic',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Furnace Master',
                'description' => 'Burn 50,000 total calories',
                'achievement_type' => 'calories',
                'criteria_json' => ['target_calories' => 50000],
                'points_value' => 250,
                'badge_icon' => 'bonfire',
                'badge_color' => '#F59E0B',
                'rarity_level' => 'legendary',
                'is_active' => true,
            ],

            // ===== TIME/DURATION ACHIEVEMENTS =====
            [
                'achievement_name' => 'First Hour',
                'description' => 'Train for 60 total minutes',
                'achievement_type' => 'time',
                'criteria_json' => ['target_minutes' => 60],
                'points_value' => 25,
                'badge_icon' => 'time',
                'badge_color' => '#6B7280',
                'rarity_level' => 'common',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Dedicated',
                'description' => 'Train for 300 total minutes (5 hours)',
                'achievement_type' => 'time',
                'criteria_json' => ['target_minutes' => 300],
                'points_value' => 50,
                'badge_icon' => 'time',
                'badge_color' => '#6B7280',
                'rarity_level' => 'common',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Time Investor',
                'description' => 'Train for 600 total minutes (10 hours)',
                'achievement_type' => 'time',
                'criteria_json' => ['target_minutes' => 600],
                'points_value' => 75,
                'badge_icon' => 'hourglass',
                'badge_color' => '#3B82F6',
                'rarity_level' => 'rare',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Marathon Mind',
                'description' => 'Train for 1,500 total minutes (25 hours)',
                'achievement_type' => 'time',
                'criteria_json' => ['target_minutes' => 1500],
                'points_value' => 150,
                'badge_icon' => 'stopwatch',
                'badge_color' => '#8B5CF6',
                'rarity_level' => 'epic',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Time Lord',
                'description' => 'Train for 3,000 total minutes (50 hours)',
                'achievement_type' => 'time',
                'criteria_json' => ['target_minutes' => 3000],
                'points_value' => 250,
                'badge_icon' => 'time',
                'badge_color' => '#F59E0B',
                'rarity_level' => 'legendary',
                'is_active' => true,
            ],

            // ===== SOCIAL ACHIEVEMENTS =====
            [
                'achievement_name' => 'Team Player',
                'description' => 'Complete your first group workout',
                'achievement_type' => 'social',
                'criteria_json' => ['target_group_workouts' => 1],
                'points_value' => 50,
                'badge_icon' => 'people',
                'badge_color' => '#6B7280',
                'rarity_level' => 'common',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Group Regular',
                'description' => 'Complete 5 group workouts',
                'achievement_type' => 'social',
                'criteria_json' => ['target_group_workouts' => 5],
                'points_value' => 100,
                'badge_icon' => 'people',
                'badge_color' => '#3B82F6',
                'rarity_level' => 'rare',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Pack Leader',
                'description' => 'Complete 10 group workouts',
                'achievement_type' => 'social',
                'criteria_json' => ['target_group_workouts' => 10],
                'points_value' => 125,
                'badge_icon' => 'people-circle',
                'badge_color' => '#3B82F6',
                'rarity_level' => 'rare',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Motivator',
                'description' => 'Complete 25 group workouts',
                'achievement_type' => 'social',
                'criteria_json' => ['target_group_workouts' => 25],
                'points_value' => 175,
                'badge_icon' => 'megaphone',
                'badge_color' => '#8B5CF6',
                'rarity_level' => 'epic',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Community Legend',
                'description' => 'Complete 50 group workouts',
                'achievement_type' => 'social',
                'criteria_json' => ['target_group_workouts' => 50],
                'points_value' => 300,
                'badge_icon' => 'star',
                'badge_color' => '#F59E0B',
                'rarity_level' => 'legendary',
                'is_active' => true,
            ],

            // ===== LEVEL PROGRESSION ACHIEVEMENTS =====
            [
                'achievement_name' => 'Welcome Newcomer',
                'description' => 'Start your fitness journey as a beginner',
                'achievement_type' => 'special',
                'criteria_json' => ['level' => 'beginner', 'type' => 'level_progression'],
                'points_value' => 10,
                'badge_icon' => 'person-add',
                'badge_color' => '#10B981',
                'rarity_level' => 'common',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Rising Star',
                'description' => 'Reach intermediate fitness level',
                'achievement_type' => 'special',
                'criteria_json' => ['level' => 'intermediate', 'type' => 'level_progression'],
                'points_value' => 100,
                'badge_icon' => 'trending-up',
                'badge_color' => '#3B82F6',
                'rarity_level' => 'rare',
                'is_active' => true,
            ],
            [
                'achievement_name' => 'Elite Athlete',
                'description' => 'Reach advanced fitness level',
                'achievement_type' => 'special',
                'criteria_json' => ['level' => 'advanced', 'type' => 'level_progression'],
                'points_value' => 200,
                'badge_icon' => 'rocket',
                'badge_color' => '#8B5CF6',
                'rarity_level' => 'epic',
                'is_active' => true,
            ],
        ];

        foreach ($achievements as $achievement) {
            Achievement::updateOrCreate(
                ['achievement_name' => $achievement['achievement_name']],
                array_merge($achievement, [
                    'criteria_json' => json_encode($achievement['criteria_json']),
                ])
            );
        }

        $this->command->info('Seeded ' . count($achievements) . ' achievements.');
    }
}
